[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:8080 --workers 1 --timeout 120"
healthcheckPath = "/api/status"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "8080"
