name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest || echo "No tests found"

    - name: Deploy to Railway
      uses: railway-app/actions@v1
      with:
        api-token: ${{ secrets.RAILWAY_TOKEN }}
        command: up
      if: github.ref == 'refs/heads/main'
